version: '3.3'
networks: {rasa-network: {}}
services:
  rasa:
    image: rasa/rasa:latest-full
    ports:
      - "5005:5005"
    volumes:
      - ./rasa/models/openHPI_de:/app/models/openHPI_de/
    command: ["run", "-vv", "--enable-api", "--endpoints", "endpoints.yml", "--credentials", "credentials.yml"]
    networks: ['rasa-network']
    depends_on:
      - duckling
  duckling:
    image: rasa/duckling:latest
    ports:
      - "8000:8000"
    networks: ['rasa-network']