version: '3.3'
networks: {rasa-network: {}}
services:
  rasa:
    image: openhpi:1.0
    ports:
      - "5005:5005"
    command:  run -vv -m /app/models/openHPI_de/ --enable-api --endpoints /app/endpoints.yml --credentials /app/credentials.yml
    networks: ['rasa-network']
    depends_on:
      - duckling
  duckling:
    image: rasa/duckling:latest
    ports:
      - "8000:12345"
    networks: ['rasa-network']