version: '3.3'
networks: {rasa-network: {}}
services:
  rasa:
    image: openwho:2.0
    ports:
      - "54321:5005"
    command:  run -vv -m /app/models/ --enable-api --endpoints /app/endpoints.yml --credentials /app/credentials.yml --cors "*"
    networks: ['rasa-network']
    depends_on:
      - duckling
  duckling:
    image: rasa/duckling:latest
    ports:
      - "3000:3000"
    networks: ['rasa-network']